apiVersion: v1
kind: Pod
metadata:
  name: { pod-name }
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: KEY1
          value: 'value1'
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      ports:
        - containerPort: 80
