apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { statefulset-name }
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: '{{service-name}}'
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: { container-name }
          image: busybox
          args:
            - sleep
            - infinity
          volumeMounts:
            - mountPath: '/data'
              name: { volume-name }
  volumeClaimTemplates:
    - metadata:
        name: csi-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: do-block-storage
